// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hata0/travel-api/internal/usecase (interfaces: TripUsecase)
//
// Generated by this command:
//
//	mockgen -destination mock/trip.go github.com/hata0/travel-api/internal/usecase TripUsecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	output "github.com/hata0/travel-api/internal/usecase/output"
	gomock "go.uber.org/mock/gomock"
)

// MockTripUsecase is a mock of TripUsecase interface.
type MockTripUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockTripUsecaseMockRecorder
	isgomock struct{}
}

// MockTripUsecaseMockRecorder is the mock recorder for MockTripUsecase.
type MockTripUsecaseMockRecorder struct {
	mock *MockTripUsecase
}

// NewMockTripUsecase creates a new mock instance.
func NewMockTripUsecase(ctrl *gomock.Controller) *MockTripUsecase {
	mock := &MockTripUsecase{ctrl: ctrl}
	mock.recorder = &MockTripUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripUsecase) EXPECT() *MockTripUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTripUsecase) Create(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTripUsecaseMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTripUsecase)(nil).Create), ctx, name)
}

// Delete mocks base method.
func (m *MockTripUsecase) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTripUsecaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTripUsecase)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockTripUsecase) Get(ctx context.Context, id string) (output.GetTripOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(output.GetTripOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTripUsecaseMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTripUsecase)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockTripUsecase) List(ctx context.Context) (output.ListTripOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].(output.ListTripOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTripUsecaseMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTripUsecase)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockTripUsecase) Update(ctx context.Context, id, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTripUsecaseMockRecorder) Update(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTripUsecase)(nil).Update), ctx, id, name)
}
