// Code generated by MockGen. DO NOT EDIT.
// Source: travel-api/internal/domain (interfaces: TripRepository)
//
// Generated by this command:
//
//	mockgen -destination mock/trip.go travel-api/internal/domain TripRepository
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"
	domain "travel-api/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockTripRepository is a mock of TripRepository interface.
type MockTripRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTripRepositoryMockRecorder
	isgomock struct{}
}

// MockTripRepositoryMockRecorder is the mock recorder for MockTripRepository.
type MockTripRepositoryMockRecorder struct {
	mock *MockTripRepository
}

// NewMockTripRepository creates a new mock instance.
func NewMockTripRepository(ctrl *gomock.Controller) *MockTripRepository {
	mock := &MockTripRepository{ctrl: ctrl}
	mock.recorder = &MockTripRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripRepository) EXPECT() *MockTripRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTripRepository) Create(ctx context.Context, trip domain.Trip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, trip)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTripRepositoryMockRecorder) Create(ctx, trip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTripRepository)(nil).Create), ctx, trip)
}

// Delete mocks base method.
func (m *MockTripRepository) Delete(ctx context.Context, trip domain.Trip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, trip)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTripRepositoryMockRecorder) Delete(ctx, trip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTripRepository)(nil).Delete), ctx, trip)
}

// FindByID mocks base method.
func (m *MockTripRepository) FindByID(ctx context.Context, id domain.TripID) (domain.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTripRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTripRepository)(nil).FindByID), ctx, id)
}

// FindMany mocks base method.
func (m *MockTripRepository) FindMany(ctx context.Context) ([]domain.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", ctx)
	ret0, _ := ret[0].([]domain.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMany indicates an expected call of FindMany.
func (mr *MockTripRepositoryMockRecorder) FindMany(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockTripRepository)(nil).FindMany), ctx)
}

// Update mocks base method.
func (m *MockTripRepository) Update(ctx context.Context, trip domain.Trip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, trip)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTripRepositoryMockRecorder) Update(ctx, trip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTripRepository)(nil).Update), ctx, trip)
}
