services:
  app:
    build: .
    user: root 
    volumes:
      - .:/home/developer/workspace
      - go-mod-cache:/go/pkg/mod
      - gemini-cache:/root/.gemini
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    tty: true
  dev-db:
    image: postgres:17.5-bookworm
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_pass
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  dev-db-data:
  go-mod-cache:
  gemini-cache:
